# Academic Pages customization for zhangzijian0830.github.io
locale                   : "zh-CN"
site_theme               : "default"
title                    : "张子健"
title_separator          : "-"
name                     : &name "张子健"
description              : &description "张子健的学术个人主页"
url                      : "https://zhangzijian0830.github.io"
baseurl                  : ""
repository               : "zhangzijian0830/zhangzijian0830.github.io"
author:
  avatar                 : "profile.jpg.jpg"
  name                   : "张子健"
  bio                    : "南京大学新闻传播学院 2026 级传播学硕士研究生"
  location               : "南京，中国"
  employer               : "南京大学新闻传播学院"
  email                  : "tzekincheung@smail.nju.edu.cn"
  github                 : "zhangzijian0830"
markdown                 : kramdown
permalink                : /:categories/:title/
timezone                 : Asia/Shanghai
include:
  - _pages
  - files
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
